if(PARADOX_COMPILER STREQUAL "msvc")
    
elseif(PARADOX_COMPILER STREQUAL "gcc")
    set(GCC ON)
elseif(PARADOX_COMPILER STREQUAL "clang")
    set(Clang ON)
elseif(PARADOX_COMPILER STREQUAL "xcode")
    set(XCode ON)
else()
    message(FATAL_ERROR "Please set PARADOX_COMPILER to either msvc, gcc, clang, or xcode")
endif()

if((${CMAKE_BUILD_TYPE} STREQUAL "Release") OR (${CMAKE_BUILD_TYPE} STREQUAL "release"))
    set(PARADOX_RELEASE ON)
elseif((${CMAKE_BUILD_TYPE} STREQUAL "Debug") OR (${CMAKE_BUILD_TYPE} STREQUAL "debug"))
    set(PARADOX_DEBUG ON)
    set(PARADOX_MSVC_DEBUG_FLAGS /W4 /WX)
    set(PARADOX_CLANG_DEBUG_FLAGS -Og -Wpedantic -Wall -Wextra -Werror)
    set(PARADOX_GCC_DEBUG_FLAGS -Og -Wpedantic -Wall -Wextra -Werror)
else()
    message(FATAL_ERROR "Please set CMAKE_BUILD_TYPE to either Release or Debug" )
endif()

if(WIN32)
    if(MSVC)
        set(PARADOX_CXX_DEBUG_FLAGS ${PARADOX_MSVC_DEBUG_FLAGS})
    elseif(Clang)
        set(PARADOX_CXX_DEBUG_FLAGS ${PARADOX_CLANG_DEBUG_FLAGS})
    elseif(GCC)
        set(PARADOX_CXX_DEBUG_FLAGS ${PARADOX_GCC_DEBUG_FLAGS})
    endif()
    set(PARADOX_C_COMPILE_DEFINITIONS ${PARADOX_C_COMPILE_DEFINITIONS} _CRT_SECURE_NO_DEPRECATE)
elseif(LINUX)
    if(Clang)
        set(PARADOX_CXX_DEBUG_FLAGS ${PARADOX_CLANG_DEBUG_FLAGS})
    elseif(GCC)
        set(PARADOX_CXX_DEBUG_FLAGS ${PARADOX_GCC_DEBUG_FLAGS})
    endif()
elseif(APPLE)
    if(XCode)
        set(PARADOX_SWIFT_DEBUG_FLAGS ${PARADOX_XCODE_DEBUG_FLAGS})
    elseif(Clang)
        set(PARADOX_CXX_DEBUG_FLAGS ${PARADOX_CLANG_DEBUG_FLAGS})
    elseif(GCC)
        set(PARADOX_CXX_DEBUG_FLAGS ${PARADOX_GCC_DEBUG_FLAGS})
    endif()
endif()

if(PARADOX_RELEASE)
    set(PARADOX_CXX_COMPILE_FLAGS ${PARADOX_CXX_COMPILE_FLAGS} ${PARADOX_CXX_RELEASE_FLAGS})
elseif(PARADOX_DEBUG)
    set(PARADOX_CXX_COMPILE_FLAGS ${PARADOX_CXX_COMPILE_FLAGS} ${PARADOX_CXX_DEBUG_FLAGS})
endif()
