# Sets up the general library options
# PARADOX_BUILD_LANG for single language build
macro(paradox_library_options)
    option(PARADOX_BUILD_C_LIBS "Builds static|shared C libraries" ON)
    option(PARADOX_BUILD_CXX_LIBS "Builds static|shared C++ libraries" ON)
    option(PARADOX_BUILD_Swift_LIBS "Builds Swift libraries" ON)
    option(PARADOX_BUILD_SHARED_LIBS "Builds shared libraries" ON)
    if(PARADOX_BUILD_CXX_LIBS OR PARADOX_BUILD_C_LIBS OR PARADOX_BUILD_Swift_LIBS)
        set(PARADOX_BUILD_LIB ON)
    endif()
endmacro()

macro(paradox_tests_options)
    option(PARADOX_BUILD_TESTS "Builds the test cases" OFF)
endmacro()

macro(paradox_documentation_options)
    option(PARADOX_BUILD_DOCS "Builds the documentation" OFF)
endmacro()

if("${PARADOX_BUILD_LANG}" STREQUAL "C")
    set(CMAKE_C_STANDARD 11)
    set(CMAKE_C_STANDARD_REQUIRED ON)
    set(CMAKE_C_EXTENSIONS ON)
elseif("${PARADOX_BUILD_LANG}" STREQUAL "CXX")
    set(CMAKE_CXX_STANDARD 11)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_EXTENSIONS ON)
elseif("${PARADOX_BUILD_LANG}" STREQUAL "Swift")
endif()